### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by isural** [dadasoz/edx-bootstrap-theme#2]
Hi

It is looks good. I tried to enable in my edx installation but got error in compiling after paver update_assets lms --settings=aws command.
Thanks for help

CompileError: Error: File to import not found or unreadable: lms/static/sass/lms-main-rtl
       Parent style sheet: /edx/app/edxapp/edx-platform/themes/edx-bootstrap-theme/lms/static/sass/lms-main-rtl.scss
        on line 5 of themes/edx-bootstrap-theme/lms/static/sass/lms-main-rtl.scss

> > @import 'lms/static/sass/lms-main-rtl';
> >    ^

**Comment by dadasoz** [comment]
@isural 

use branch develop

`git checkout develop`

**Comment by isural** [comment]
I really don't understand what i am doing wrong. 

I got   

File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/sass.py", line 223, in compile_dirname
    encoding="UTF-8") as output_file:
IOError: [Errno 13] Permission denied: '/edx/app/edxapp/edx-platform/themes/edx-bootstrap-theme/lms/static/css/lms-main-v1.css'

I have checked folder and there was no lms-main-v1.css.

Command List I used:

$ git clone https://github.com/dadasoz/edx-bootstrap-theme.git
$ git checkout develop
$ sudo su edxapp -s /bin/bash
$ cd ~
$ source edxapp_env
$ cd /edx/app/edxapp/edx-platform
$ paver update_assets lms --settings=aws

Thnaks for your help

**Comment by ashay-maheshwari** [comment]
@isural , I faced the same error which I resolved by giving 777 permissions to my themes folder in /edx/app/edxapp/themes
