### ISSUE TITLE
Do I need to install bootstrap ??

### ISSUE THREAD

**Issue by ashay-maheshwari** [dadasoz/edx-bootstrap-theme#3]
Hello Friend, that is a great effort and people like me are to consume without efforts.
I tried applying your theme and followed the instructions. 

I got a "No CSS"??? look. Means I need to download bootstrap ??
If it is the case can you guide me how to use that downloaded bootstrap.

**Comment by dadasoz** [comment]
@ashay-maheshwari  You dont need to install bootstrap manually, Its already there.

**Comment by ashay-maheshwari** [comment]
Thanks Friend it is working for me on Dogwood 3
